name: bol_food_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^9.2.4
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  geolocator: ^10.1.0
  socket_io_client: ^2.0.3+1
  permission_handler: ^11.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
